import 'package:flutter/material.dart';

// Define a new widget for displaying category text
class CategoryTextWidget extends StatelessWidget {
  final String category;

  const CategoryTextWidget({Key? key, required this.category}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    String categoryText = _getTextForCategory(category);

    return Padding(
      padding: const EdgeInsets.fromLTRB(16.0, 0, 16.0, 16.0),
      child: Text(
              categoryText,
              style: TextStyle(
              color: Colors.grey.shade50,
              fontSize: 15.0,)),
    );
  }

  String _getTextForCategory(String category) {
    switch (category) {
      case 'Privacy Policy':
        return
          'This Privacy Policy describes Our policies and procedures '
          'on the collection, use and disclosure of Your information '
          'when You use the Service and tells You about Your privacy rights '
          'and how the law protects You.\n\n'
          'We use Your Personal data to provide and improve the Service. '
          'By using the Service, You agree to the collection and use of information '
          'in accordance with this Privacy Policy.';

      case 'Definitions':
        return '''
For the purposes of this Privacy Policy:

- Account means a unique account created for You to access our Service or parts of our Service.

- Application refers to MenuCraft, the software program provided by the Company.

- Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to MenuCraft.

- Country refers to: Macedonia

- Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

- Personal Data is any information that relates to an identified or identifiable individual.

- Service refers to the Application.

- Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

- Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.

- Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

- You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.''';

      case 'Personal Data':
        return '''
While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:

  - Email address

  - First name and last name

  - Address

  - Usage Data''';

      case 'Usage Data':
        return
          'Usage Data is collected automatically when using the Service.'
          'When You access the Service by or through a mobile device, '
          'We may collect certain information automatically, including, '
          'but not limited to, the type of mobile device You use, Your mobile device '
          'unique ID, the IP address of Your mobile device, Your mobile operating system, '
          'unique device identifiers and other diagnostic data';

      case 'Information from Third-Party Social Media Services':
        return 'Text';

      case 'Information Collected while Using the Application':
        return 'Text';

      case 'Use of Your Personal Data':
        return 'Text';

      case 'Retention of Your Personal Data':
        return 'Text';

      case 'Delete Your Personal Data':
        return 'Text';

      case 'Security of Your Personal Data':
        return 'Text';

      case 'Changes to this Privacy Policy':
        return 'Text';

      default:
        return '';
    }
  }
}